name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, linux, dev1]
    steps:
      - run: echo "Hello from Gihub Actions !!!"
